"""empty message

Revision ID: b1b16c78c22
Revises: 1e64b62c3a3f
Create Date: 2014-08-07 19:13:55.216000

"""

# revision identifiers, used by Alembic.
revision = 'b1b16c78c22'
down_revision = '1e64b62c3a3f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_column('article', 'data_created')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('data_created', mysql.DATETIME(), nullable=True))
    op.drop_column('article', 'date_created')
    ### end Alembic commands ###
